<!DOCTYPE html>
<html lang="ja" dir="ltr">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
	<meta name="theme-color" content="#000000" />
	<meta name="robots" content="noindex, nofollow" />
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<title>Liff Starter</title>
</head>
<body>
	<p id="liffAppContent"></p>
	<p id="liffInitErrorMessage"></p>
	<p id="browserLanguage"></p>
	<p id="sdkVersion"></p>
	<p id="isLoggedIn"></p>
	<p id="deviceOS"></p>
	<button type="button" id="liffLoginButton">Login</button>

	<script src="https://static.line-scdn.net/liff/edge/2.1/sdk.js"></script>
	<script>
		const myLiffId = '1653921037-gL5vYr8p';

		/**
		 * Initialize LIFF
		 * @param {string} myLiffId The LIFF ID of the selected element
		 */
		function initializeLiff(myLiffId) {
			liff.init({
				liffId: myLiffId
			}).then(() => {
				// start to use LIFF's api
				initializeApp();
			}).catch(error => {
				document.getElementById('liffAppContent').classList.add('hidden');
				document.getElementById('liffInitErrorMessage').classList.remove('hidden');
			});
		}

		/**
		 * Display data generated by invoking LIFF methods
		 */
		function displayLiffData() {
			document.getElementById('browserLanguage').textContent = liff.getLanguage();
			document.getElementById('sdkVersion').textContent = liff.getVersion();
			document.getElementById('isInClient').textContent = liff.isInClient();
			document.getElementById('isLoggedIn').textContent = liff.isLoggedIn();
			document.getElementById('deviceOS').textContent = liff.getOS();
		}

		initializeLiff(myLiffId);
		displayLiffData();

	</script>
</body>
</html>
